services:
  popcorn-pos:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=postgresql://popcorn_user:PoPcorn@234@postgres:5432/popcorn_pos
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secure-session-secret-key-minimum-32-characters}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3002}
      - NEON_DISABLE_WEBSOCKETS=true
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3002/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: popcorn_pos
      POSTGRES_USER: popcorn_user
      POSTGRES_PASSWORD: PoPcorn@234
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U popcorn_user"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  postgres_data:
