services:
  popcorn-pos-beta:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://popcorn_user:PoPcorn@1234@cmctbo8fv001pqsa3j2268dw6:5432/popcorn_pos_beta
      - SESSION_SECRET=${SESSION_SECRET:-beta_testing_secret_key_minimum_32_characters_long}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:3003}
      - NEON_DISABLE_WEBSOCKETS=true
      - DEMO_MODE=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s